### ISSUE TITLE
Implement 2.01 "4. A consistent approach to multi-lingual names, descriptions and free text."

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Schemas#68]
http://support.iatistandard.org/entries/45539933-Thematic-content-agreed-by-IATI-Steering-Committee

http://support.iatistandard.org/entries/56804973-Version-2-01-Iteration-1-4-Multi-lingual-text-fields

**Comment by bill-anderson** [comment]
NB. That http://iati.titanpad.com/72 deals with activity standard. Needs to be applied to organisation standard as well

**Comment by Bjwebb** [comment]
For anyone following this github issue who doesn't have access to the IATI Titanpads, the above link contains the list of elements that nows appears in the proposal at http://support.iatistandard.org/entries/56804973-Version-2-01-Iteration-1-4-Multi-lingual-text-fields

**Comment by Bjwebb** [comment]
We created a list of elements we are removing text from, or changing the way multilingual text is done, and noted why they have an `xml:lang` attribute.
https://docs.google.com/spreadsheets/d/1mIcyBAkeOxUbU_EOK4vQI3uUnMIdI500TqlXVYhQtAM/edit#gid=0

We also plan to make all elements `mixed="false"`. https://github.com/IATI/IATI-Schemas/issues/112 (although what we will actually do is remove `mixed="true"`). This will help us enforce the requirement that most elements don't contain text directly.

This spreadsheet showed that we could make the required changes by:

### Removing textAtts (from elements that do not require any text, only codes) from:
- codeType
- codeReqType
- refType
- policy-marker (NB this may need to be altered (RO option?))
- recipient-region
- recipient-country
- related-activity

### Adding the narrative element to elements that can have multilingual values

These elements currently reference textAtts or textType, so we can do this by...
1) Creating a narrative element under the 'common elements' section of the common schema
2) Removing textAtts, and adding a ref to the new narrative element:
This involves changing a lot of

``` xml
<xsd:sequence>
  <xsd:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attributeGroup ref="textAtts"/>
```

to

``` xml
<xsd:choice minOccurs="0" maxOccurs="unbounded">
  <xsd:element ref="narrative" />
  <xsd:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
</xsd:choice>
```

...on these types and elements
- textType
- activity-date
- reporting-org
- participating-org
- description
- country-budget-items/budget-item/description
- conditions/condition
- sector
- iati-organisation/name

3) Using textType instead of textAtts:
- contact-info/mailing-address

4) Delete unused types/ attribute groups:
- textAtts
- indicatorOutcomeType [this wasn't used in 1.04... currently in activity schema at: https://github.com/IATI/IATI-Schemas/blob/version-1.04/iati-activities-schema.xsd#L1461]

**Comment by Bjwebb** [comment]
Outstanding questions/tasks:
- [x] `policy-marker` is currently planned to have text removed, but we're not sure whether this is correct, because like sector it can have a Reporting Org defined vocabulary.
- [x] Remove all `mixed="true"` https://github.com/IATI/IATI-Schemas/issues/112
- [x] Update schema tests to support changes https://github.com/IATI/IATI-Schemas/pull/120

**Comment by Bjwebb** [comment]
The following narrative elements have been added, which were missing from our previous list:
- policy-marker/narrative
- transaction/provider-org/narrative
- transaction/receiver-org/narrative
- transaction-date/narrative

**Comment by caprenter** [comment]
location/administrative is missing from the list on
http://support.iatistandard.org/entries/77309847-Version-2-01-Iteration-2-4-Multi-lingual-text-fields

**Comment by bill-anderson** [comment]
location/administrative is missing from the list on
http://support.iatistandard.org/entries/77309847-Version-2-01-Iteration-2-4-Multi-lingual-text-fields

Done

**Comment by Bjwebb** [comment]
Following the [change to the proposal](http://support.iatistandard.org/entries/77309847-Version-2-01-Iteration-2-4-Multi-lingual-text-fields#view-post-22174599), I have added narrative elements to all recipient-country and recipient-region elements.

BTW, @bill-anderson is transaction-date still missing from [the list](http://support.iatistandard.org/entries/77309847-Version-2-01-Iteration-2-4-Multi-lingual-text-fields)? It currently has a narrative subelement in the schema.

**Comment by caprenter** [comment]
I believe this is now complete.
transaction-date should not have had a narrative element and that has since been removed from the schema in this commit: https://github.com/IATI/IATI-Schemas/commit/66e72a4695c4130e5cd09d23d67b5c30e701ea1b
